//next imports
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";

//react imports
//installed components imports
import 'bootstrap/dist/css/bootstrap.css';
import { Col } from "react-bootstrap";
//custom components imports
import { ClientNavWrapper } from "./components/ClientNavWrapper";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Growthspring Club | Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const userName = headers().get('user-name')!
  const names = userName.split(" ")
  const displayName = names[names.length -1 ]

  return (
    <html lang="en">
      <body className = {inter.className}>
        <div>
          <ClientNavWrapper adminName = { displayName} />
          <Col className="" lg = {{  offset: 3 }}  >
            {children}
          </Col>
        </div>
      </body>
    </html>
  );
}
