//next imports
import type { Metadata } from "next";
import { Inter } from "next/font/google";
//react imports
//installed components imports
import 'bootstrap/dist/css/bootstrap.css';
import { Col } from "react-bootstrap";
//custom components imports
import { ClientNavWrapper } from "./components/ClientNavWrapper";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className = {inter.className}>
        <div>
          <ClientNavWrapper/>
          <Col className="px-3" md = {{  offset: 3 }}  >
            {children}
          </Col>
        </div>
      </body>
    </html>
  );
}
